feat: Implement push notification module and microservice
credebl/platform pull request #426
Opened 2024-01-09 07:02 UTC by KulkarniShashank

### What ###

- Added a push notification module to enable real-time updates.
- Created a push notification microservice for handling notification logic.

### Why ###

- Improved user engagement by providing timely updates and notifications.
- Separated notification functionality into a microservice for scalability and maintainability.

### How ###

- Added API endpoint for registering organization webhooks.
- Implemented API for storing FCM tokens, user keys, and organization IDs.
- Ensured proper validation and security measures in API endpoints.

2024-01-17 07:22 UTC, ankita-p17 requested changes

2024-01-17 07:22 UTC, ankita-p17 commented on apps/organization/dtos/create-organization.dto.ts
> +  webhookEndpoint?: string;
Please update this variable name similar to notificationWebhook

2024-01-18 11:01 UTC, sairanjit requested changes
I have a few questions here based on our last discussion

- Do we need to store fcm tokens ?
- Do we need to map userkey ?

2024-01-19 08:18 UTC, KulkarniShashank commented
> I have a few questions here based on our last discussion
> 
> * Do we need to store fcm tokens ?

- No, we not stored the fcm token

> * Do we need to map userkey ?

- Certainly, when modifying the notification webhook, it is necessary to obtain the revised notification webhook by utilizing the userkey.

2024-01-19 08:19 UTC, KulkarniShashank commented
> > I have a few questions here based on our last discussion
> 
> > * Do we need to store fcm tokens ?
> 
> * No, we not stored the fcm token
> 
> > * Do we need to map userkey ?
> 
> * Certainly, when modifying the notification webhook, it is necessary to obtain the revised notification webhook by utilizing the userkey.

2024-02-06 11:03 UTC, ankita-p17 approved these changes

2024-02-06 11:11 UTC, ankita-p17 approved these changes

2024-02-19 14:28 UTC, closed without merging