refactor: support auto flag for connection, issuance and verification
credebl/platform pull request #477
Opened 2024-02-01 12:19 UTC by KulkarniShashank

### What ###
Refactored the codebase to introduce an "auto" flag, enhancing support for automatic handling during connection, issuance, and verification processes.

### Why ###
The addition of the "auto" flag streamlines the user experience by automating key steps in connection, issuance, and verification. 

### How ###
Modified the relevant functions and modules to incorporate the "auto" flag, ensuring seamless execution of the specified processes. The flag can be toggled to enable or disable automatic handling based on user preferences.

2024-02-05 08:48 UTC, ankita-p17 requested changes

2024-02-05 08:48 UTC, ankita-p17 commented on apps/connection/src/connection.service.ts
> +        label: label || undefined
Please take organisation.name as well here

2024-02-06 06:18 UTC, ankita-p17 approved these changes

2024-02-06 06:55 UTC, nishad-ayanworks approved these changes
LG

2024-02-06 06:56 UTC, merged