feat: agent configure
credebl/platform pull request #713
Opened 2024-05-13 07:45 UTC by KulkarniShashank

### What ###
Implementing the Agent configure API, which allows for the configuration of agents within the system.

### Why ###
The Agent configure API is essential for enabling dynamic configuration of agents, providing flexibility and adaptability to changing requirements.

### How ###
Define the endpoints and payloads required for the Agent configure API.
Implement backend logic to process configuration requests and update agent settings accordingly.

2024-05-14 06:40 UTC, bhavanakarwade commented on libs/common/src/cast.helper.ts
> +  private static validateWalletName(walletName: string): void {
There is no need to validate the wallet name, as the agent accepts alphanumeric characters

2024-05-14 07:00 UTC, bhavanakarwade requested changes

2024-05-16 07:26 UTC, bhavanakarwade approved these changes
LG

2024-05-16 08:09 UTC, tipusinghaw approved these changes

2024-05-16 08:09 UTC, merged