fix: API refactor in user, organization, auth and agent module
credebl/platform pull request #82
Opened 2023-09-13 12:57 UTC by KulkarniShashank

### What ###

1. Refactored the API endpoints in the user, organization, and agent modules.
2. Improved code organization and readability.
3. Addressed code duplication and inefficiencies.
4. Updated API documentation.

### Why ###

1. To enhance the maintainability of the codebase by reducing complexity and improving structure.
2. To eliminate code redundancy and ensure consistency across the modules.
3. To provide better support for future feature development.
4. To make the API more user-friendly and intuitive for developers.

### How ###

1. Reviewed the existing codebase in the user, organization, and agent modules.
2. Identified areas for improvement, including code duplication and inconsistent naming.
3. Refactored the API endpoints using best practices and design patterns.
4. Updated API documentation to reflect the changes made.
5. Ran tests to ensure that the refactored code functions correctly.

2023-09-14 11:15 UTC, nishad-ayanworks commented on apps/api-gateway/src/user/user.controller.ts
> +  @Get('/orgs/:orgId/users')
Please move this API to the `orgs` controller

2023-09-14 11:18 UTC, nishad-ayanworks commented on apps/api-gateway/src/user/user.controller.ts
> +  @Get('/users/org-invitations')
If `/users` is repeating for all the APIs. you can set it to the top inside `@Controllers('users')`

2023-09-14 11:20 UTC, nishad-ayanworks requested changes
Please resolve the comments

2023-09-15 07:46 UTC, nishad-ayanworks commented on apps/api-gateway/common/exception-handler.ts
> +    } else if (exception["statusCode"] === undefined && status === HttpStatus.INTERNAL_SERVER_ERROR) {
Please check if `exception` is available on line 26

2023-09-15 07:48 UTC, nishad-ayanworks commented on apps/api-gateway/src/authz/authz.service.ts
> +  async addUserDetailsInKeyCloak(userInfo: AddUserDetails): Promise<{ response: string }> {
Please remove this function if we are not using

2023-09-15 07:50 UTC, nishad-ayanworks commented on apps/api-gateway/src/organization/organization.controller.ts
> +  @Get('/public-profile')
please update API endpoint with `/public-profiles`

2023-09-15 07:53 UTC, nishad-ayanworks commented on apps/api-gateway/src/organization/organization.controller.ts
>    @UseGuards(AuthGuard('jwt'))
Please include `OrgRoleGuard` in the @UseGuards

2023-09-15 07:56 UTC, nishad-ayanworks commented on apps/api-gateway/src/organization/organization.controller.ts
> +  @UseGuards(AuthGuard('jwt'))
Include `OrgRoleGuard`

2023-09-15 08:01 UTC, nishad-ayanworks commented on apps/api-gateway/src/user/user.controller.ts
> +  @Roles(OrgRoles.OWNER, OrgRoles.SUPER_ADMIN, OrgRoles.ADMIN, OrgRoles.ISSUER, OrgRoles.VERIFIER, OrgRoles.MEMBER)
Please remove the `Roles` and `OrgRoleGuard` from the user activity API. It is user specific API

2023-09-15 08:02 UTC, nishad-ayanworks commented on apps/api-gateway/src/user/user.controller.ts
> +      message: 'User activities fetched successfully',
Please move this message to common library

2023-09-15 08:04 UTC, nishad-ayanworks requested changes
Please check comments

2023-09-20 06:12 UTC, tipusinghaw approved these changes
LGTM

2023-09-20 06:21 UTC, nishad-ayanworks approved these changes
LG

2023-09-20 06:21 UTC, merged